# MongoDB
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=price

# PostgreSQL
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# External APIs
scraper.api.url=https://scrap-product-server.onrender.com
prediction.api.url=https://python-prediction-server.onrender.com

# Admin Email
app.email.admin=krishna30mar@gmail.com
app.email.from=${MAIL_USERNAME}

# Server
server.port=8080